### ISSUE TITLE
Add custom CSS classes and field type to outputted fields

### ISSUE THREAD

**Issue by ovann86** [blueliquiddesigns/gravity-forms-pdf-extended#8]
Hi,

I'm not all that familiar with using GitHub, but would like to suggest a change that would add the field type and any front end custom CSS classes to the outputted field.

Example can be seen here: 

https://github.com/ovann86/gravity-forms-pdf-extended/pull/1

**Comment by blueliquiddesigns** [comment]
Thanks for the feedback and pull request. 

I'm not going to merge that change in right now (not because it's not a good idea) as we have already addressed this issue in our next major release currently being worked on (I actually just finished up a *major* overhaul of the pdf-entry-detail.php this week). With that said, there's currently no scheduled release date for Gravity PDF 4.0 (we are aiming for later this year).

In the interim, you should be safe leaving those changes in your local copy and know that it will be forward compatible.

**Comment by ovann86** [comment]
Thanks. Good to know something like this is in the plans.
